name: miaaim-dev
channels:
   - conda-forge
   - bioconda
dependencies:
   - python=3.10
   - numpy
   - numba
   - matplotlib
   - pandas
   - scipy
   - scikit-learn
   - pyimzml
   - pathlib
   - uncertainties
   - pyyaml
   - tensorflow
   - umap-learn
   - dask
   - ipykernel
#   - centrosome
   - muon
   - leidenalg
   - squidpy
   - pip
   - pip:
      - centrosome
