name: miaaim-dev
channels:
   - conda-forge
   - bioconda
dependencies:
   - python=3.10
   - centrosome
   - ipykernel
   - pip
   - pip:
       - numpy
       - kneed
       - numba
       - matplotlib
       - pandas
       - scipy
       - scikit-learn
       - pyimzml
       - pathlib
       - uncertainties
       - pyyaml
       - tensorflow
       - umap-learn
       - dask
       - muon
       - leidenalg
       - squidpy
